name = "KineticEquation"
uuid = "9de4f9c8-8a19-4a2c-81f5-6cea30ccb8ad"
authors = ["biplab37 <biplabmahato37@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
